name: zero
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=51_gnu
  - blas=1.0=openblas
  - bzip2=1.0.8=h998d150_6
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - ld_impl_linux-aarch64=2.40=h48e3ba3_0
  - libffi=3.3=h7c1a80f_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h6e398d7_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libopenblas=0.3.29=h29fea54_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h998d150_0
  - libxcb=1.17.0=hf66535e_0
  - ncurses=6.5=h419075a_0
  - numpy=1.26.4=py310he45c16d_0
  - numpy-base=1.26.4=py310h15d264d_0
  - openssl=1.1.1w=h2f4d8fa_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=hfd63f10_1
  - python=3.10.0=hc137634_5
  - readline=8.3=h886d1d0_0
  - scikit-learn=1.7.1=py310h697aa12_0
  - scipy=1.15.3=py310h3e6cd32_0
  - setuptools=78.1.1=py310hd43f75c_0
  - sqlite=3.50.2=h998d150_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.14=hb5ae6a8_1
  - wheel=0.45.1=py310hd43f75c_0
  - xorg-libx11=1.8.12=hf66535e_1
  - xorg-libxau=1.0.12=hf66535e_0
  - xorg-libxdmcp=1.1.5=hf66535e_0
  - xorg-xorgproto=2024.1=h998d150_1
  - xz=5.6.4=h998d150_1
  - zlib=1.2.13=h998d150_1
  - pip:
      - accelerate==1.10.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - datasets==4.0.0
      - dill==0.3.8
      - filelock==3.18.0
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - hf-xet==1.1.7
      - huggingface-hub==0.34.4
      - idna==3.10
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - multidict==6.6.3
      - multiprocess==0.70.16
      - networkx==3.4.2
      - packaging==25.0
      - pandas==2.3.1
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - pyarrow==21.0.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.4
      - safetensors==0.6.2
      - six==1.17.0
      - speedtest-cli==2.1.3
      - sympy==1.14.0
      - tokenizers==0.21.4
      - torch==2.2.0
      - tqdm==4.67.1
      - transformers==4.49.0
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - xxhash==3.5.0
      - yarl==1.20.1
prefix: /home/nvidia/anaconda3/envs/zero
